export interface MotifItem {
  id: string
  name: string
  description: string
  imageSrc: string
  category: string
  tags: string[]
}

export const MOTIF_COLLECTION: MotifItem[] = [
  // ─── LINH VẬT ───
  {
    id: 'ga-dai-cat',
    name: 'Gà Đại Cát',
    description: 'Biểu tượng thịnh vượng, cát tường, cầu chúc may mắn đầu năm mới',
    imageSrc: '/dong-ho/rooster.png',
    category: 'linh-vat',
    tags: ['Tết', 'may mắn', 'thịnh vượng', 'linh vật'],
  },
  {
    id: 'em-be-ca-chep',
    name: 'Em bé cưỡi cá chép',
    description: 'Bức tranh Vinh Hoa biểu trưng cho khát vọng học hành đỗ đạt, vượt vũ môn hóa rồng',
    imageSrc: '/dong-ho/carp-children.png',
    category: 'linh-vat',
    tags: ['phú quý', 'may mắn', 'học hành', 'linh vật'],
  },
  {
    id: 'lon-am-duong',
    name: 'Lợn Âm Dương',
    description: 'Cặp lợn biểu trưng âm dương hòa hợp, sinh sôi nảy nở, phồn thịnh đủ đầy',
    imageSrc: '/dong-ho/0af88828eef1af6158e566567c3f3d40.jpg',
    category: 'linh-vat',
    tags: ['âm dương', 'phồn thịnh', 'sinh sôi', 'linh vật'],
  },
  {
    id: 'ca-chep-vuot-vu-mon',
    name: 'Cá Chép Vượt Vũ Môn',
    description: 'Cá chép vươn mình hóa rồng, biểu tượng cho sự kiên trì và thành công học hành',
    imageSrc: '/dong-ho/1fd9bb8d430c9de1755c3013e211243b.jpg',
    category: 'linh-vat',
    tags: ['cá chép', 'vũ môn', 'thành đạt', 'linh vật'],
  },
  {
    id: 'ga-trong-don-xuan',
    name: 'Gà Trống Đón Xuân',
    description: 'Gà trống oai vệ gáy vang chào đón bình minh, đào mai đua nở rộn ràng ngày Tết',
    imageSrc: '/dong-ho/2ab48888852a073b1ef2d5d9447ddb43.jpg',
    category: 'linh-vat',
    tags: ['Tết', 'gà trống', 'bình minh', 'linh vật'],
  },
  {
    id: 'ca-dan-choi-trang',
    name: 'Cá Đàn Chơi Trăng',
    description: 'Bầy cá tung tăng dưới ánh trăng, tượng trưng cho cuộc sống tự do, sung túc',
    imageSrc: '/dong-ho/3e38ddb5ff21db3cb2c5aa735965e420.jpg',
    category: 'linh-vat',
    tags: ['cá', 'trăng', 'tự do', 'linh vật'],
  },
  {
    id: 'long-muoi-hai-con',
    name: 'Long mười hai con',
    description: 'Rồng thiêng oai phong với mười hai chi tiết tinh xảo, biểu tượng quyền uy',
    imageSrc: '/dong-ho/6ff5a5751fa7e466b348949b8241e110.jpg',
    category: 'linh-vat',
    tags: ['rồng', 'uy quyền', 'linh thiêng', 'linh vật'],
  },
  {
    id: 'nghienh-dien-dau-hang',
    name: 'Nghinh Điền Đầu Hàng',
    description: 'Trâu vàng nghênh đón, biểu tượng cho sức mạnh và sự cần cù của làng quê Việt',
    imageSrc: '/dong-ho/7a8a48b0874e962beca2ab29eb88dafa.jpg',
    category: 'linh-vat',
    tags: ['trâu', 'sức mạnh', 'cần cù', 'linh vật'],
  },
  {
    id: 'phu-quy-sung-tuc',
    name: 'Phú Quý Sung Túc',
    description: 'Đàn lợn mẹ lợn con quây quần no đủ, chúc phúc phú quý dồi dào',
    imageSrc: '/dong-ho/8d3ff12dfd9346460b32a1d5ad347a2c.jpg',
    category: 'linh-vat',
    tags: ['lợn', 'phú quý', 'đủ đầy', 'linh vật'],
  },
  {
    id: 'tien-tai-nhu-y',
    name: 'Tiền Tài Như Ý',
    description: 'Vật phẩm may mắn kèm linh vật tượng trưng cho tiền tài, như ý, cát tường',
    imageSrc: '/dong-ho/9a0cdd102689cb54e06e1742eca81214.jpg',
    category: 'linh-vat',
    tags: ['tiền tài', 'như ý', 'cát tường', 'linh vật'],
  },
  {
    id: 'vinh-hoa-phu-quy',
    name: 'Vinh Hoa Phú Quý',
    description: 'Cá chép kết hợp mẫu đơn, biểu trưng cho vinh hoa và sự giàu sang',
    imageSrc: '/dong-ho/43c941801d97517aff46633cd268ab80.jpg',
    category: 'linh-vat',
    tags: ['vinh hoa', 'cá chép', 'giàu sang', 'linh vật'],
  },
  {
    id: 'song-hac-dong-xuan',
    name: 'Song Hạc Đón Xuân',
    description: 'Đôi hạc sải cánh trên cành tùng, mai vàng rực rỡ đón nắng xuân',
    imageSrc: '/dong-ho/43d68efd09f8ee96814b184c2f783b95.jpg',
    category: 'linh-vat',
    tags: ['hạc', 'xuân', 'trường thọ', 'linh vật'],
  },
  {
    id: 'con-cong-xoe-canh',
    name: 'Công Xòe Cánh',
    description: 'Chim công khoe sắc rực rỡ giữa vườn hoa, hòa quyện vẻ đẹp lộng lẫy',
    imageSrc: '/dong-ho/60b94473727e2ae3f1298686682087e8.jpg',
    category: 'linh-vat',
    tags: ['công', 'sắc màu', 'lộng lẫy', 'linh vật'],
  },
  {
    id: 'roi-tien-no-ngoc',
    name: 'Rồi Tiên Nở Ngọc',
    description: 'Rồng cuộn quanh châu ngọc, biểu trưng cho quyền lực và sự cao quý',
    imageSrc: '/dong-ho/098c155b35b276ed8d14a785e47fefe7.jpg',
    category: 'linh-vat',
    tags: ['rồng', 'châu ngọc', 'cao quý', 'linh vật'],
  },

  // ─── CON NGƯỜI ───
  {
    id: 'to-nu',
    name: 'Tố Nữ',
    description: 'Bức tranh tố nữ thể hiện vẻ đẹp thanh cao của các nàng nhạc công chơi nhạc cụ truyền thống',
    imageSrc: '/dong-ho/four-maidens.png',
    category: 'con-nguoi',
    tags: ['nhạc cụ', 'truyền thống', 'nghệ thuật', 'con người'],
  },
  {
    id: 'thoi-sao-dao-choi',
    name: 'Thổi sáo dạo chơi',
    description: 'Hình tượng nho sĩ thanh tao ngân nga tiếng sáo bên bóng hồng giai nhân dưới gốc liễu',
    imageSrc: '/dong-ho/scholar-flute.png',
    category: 'con-nguoi',
    tags: ['nho sĩ', 'âm nhạc', 'thư thả', 'con người'],
  },
  {
    id: 'ba-chua-cuoi-voi',
    name: 'Bà chúa cưỡi voi',
    description: 'Tích cổ oai hùng về nữ tướng Bà Triệu cưỡi voi chiến xung trận bảo vệ giang sơn',
    imageSrc: '/dong-ho/elephant-goddess.png',
    category: 'con-nguoi',
    tags: ['anh hùng', 'Bà Triệu', 'lịch sử', 'con người'],
  },
  {
    id: 'muc-dong-thoi-sao',
    name: 'Mục đồng thổi sáo',
    description: 'Cậu bé chăn trâu nằm thảnh thơi thổi sáo dưới tán lá sen khổng lồ biểu trưng cho sự bình yên',
    imageSrc: '/dong-ho/buffalo-boy.png',
    category: 'con-nguoi',
    tags: ['bình yên', 'chăn trâu', 'làng quê', 'con người'],
  },
  {
    id: 'danh-trong-ron-rang',
    name: 'Đánh Trống Rộn Ràng',
    description: 'Các chàng trai cô gái rộn ràng đánh trống mừng hội làng, không khí tưng bừng',
    imageSrc: '/dong-ho/829a727fd2d0568124fad69bfbc330bf.jpg',
    category: 'con-nguoi',
    tags: ['trống', 'hội làng', 'tưng bừng', 'con người'],
  },
  {
    id: 'thay-do-coc',
    name: 'Thầy Đồ Cóc',
    description: 'Hình ảnh châm biếm thầy đồ cóc dạy học, phản ánh xã hội xưa với nét hài hước',
    imageSrc: '/dong-ho/859a60c9293ce151305ddbaf069f2886.jpg',
    category: 'con-nguoi',
    tags: ['thầy đồ', 'châm biếm', 'hài hước', 'con người'],
  },
  {
    id: 'danh-vat',
    name: 'Đánh Vật',
    description: 'Đô vật trổ tài trong lễ hội truyền thống, thể hiện tinh thần thượng võ dân tộc',
    imageSrc: '/dong-ho/952b7ff4219df18e0f7156fb623c6100.jpg',
    category: 'con-nguoi',
    tags: ['vật', 'thượng võ', 'lễ hội', 'con người'],
  },
  {
    id: 'nong-dan-cay-cay',
    name: 'Nông Dân Cày Cấy',
    description: 'Nông dân chăm chỉ đồng áng, cày cấy mùa màng — nét đẹp lao động Việt Nam',
    imageSrc: '/dong-ho/29483bdcebaccbe62d5cf6cc5c2ca2e6.jpg',
    category: 'con-nguoi',
    tags: ['nông dân', 'lao động', 'mùa màng', 'con người'],
  },

  // ─── THIÊN NHIÊN ───
  {
    id: 'dam-sen',
    name: 'Đầm Sen',
    description: 'Sen hồng nở rộ trên mặt nước phẳng lặng, cò trắng sải cánh, đẹp thanh bình làng quê',
    imageSrc: '/dong-ho/0755334a42e665d625c9561387e2fdae.jpg',
    category: 'thien-nhien',
    tags: ['sen', 'thanh bình', 'hoa', 'thiên nhiên'],
  },
  {
    id: 'cay-dua-que-huong',
    name: 'Cây Dừa Quê Hương',
    description: 'Lũy dừa xanh mát ven sông quê, biểu tượng cho sức sống bền bỉ của làng quê Nam Bộ',
    imageSrc: '/dong-ho/bd3158898fea0c401b19b5dad35cd87d.jpg',
    category: 'thien-nhien',
    tags: ['dừa', 'sông quê', 'bền bỉ', 'thiên nhiên'],
  },
  {
    id: 'chim-ri-rung-xanh',
    name: 'Chim Ri Rừng Xanh',
    description: 'Bầy chim ri chuyền cành trong rừng xanh thẳm, thiên nhiên trù phú Bắc Bộ',
    imageSrc: '/dong-ho/c8ade633f2ad0d60acd7d28197916541.jpg',
    category: 'thien-nhien',
    tags: ['chim', 'rừng xanh', 'trù phú', 'thiên nhiên'],
  },
  {
    id: 'vuon-xuan-bach-hoa',
    name: 'Vườn Xuân Bách Hoa',
    description: 'Khu vườn mùa xuân đua nở trăm hoa, bướm lượn, ong bay vui mắt',
    imageSrc: '/dong-ho/c9d93b22ebb1f448ea6d373b7d63f1b5.jpg',
    category: 'thien-nhien',
    tags: ['xuân', 'hoa', 'bướm', 'thiên nhiên'],
  },

  // ─── PHONG TỤC ───
  {
    id: 'tay-du-ky',
    name: 'Tây Du Ký',
    description: 'Tích cổ dân gian mô tả cuộc hành trình thỉnh kinh đầy gian truân của thầy trò Đường Tăng',
    imageSrc: '/dong-ho/journey-west.png',
    category: 'phong-tuc',
    tags: ['tích cổ', 'văn hóa', 'dân gian', 'phong tục'],
  },
  {
    id: 'ruoc-den-trung-thu',
    name: 'Rước đèn Trung Thu',
    description: 'Cảnh trẻ thơ rước đèn ông sao, đèn cá chép rộn ràng dưới bóng trăng thu tròn đầy',
    imageSrc: '/dong-ho/lantern-children.png',
    category: 'phong-tuc',
    tags: ['Trung Thu', 'trẻ em', 'lễ hội', 'phong tục'],
  },
  {
    id: 'dam-cuoi-chuot',
    name: 'Đám Cưới Chuột',
    description: 'Chuột tổ chức đám cưới linh đình dâng lễ cho mèo — trào phúng sâu cay thói đời',
    imageSrc: '/dong-ho/de296016156af5a175bf925c8cb57281.jpg',
    category: 'phong-tuc',
    tags: ['chuột', 'đám cưới', 'trào phúng', 'phong tục'],
  },
  {
    id: 'huc-nhau-dip-tet',
    name: 'Húc Nhau Dịp Tết',
    description: 'Trò chơi dân gian húc nhau ngày Tết, thể hiện tinh thần thượng võ đón xuân',
    imageSrc: '/dong-ho/e2c8275566504bdc8e932600051d65de.jpg',
    category: 'phong-tuc',
    tags: ['Tết', 'trò chơi', 'dân gian', 'phong tục'],
  },
  {
    id: 'day-con-hoc-chu',
    name: 'Dạy Con Học Chữ',
    description: 'Bà mẹ dạy con học chữ nho, truyền thống hiếu học nghìn đời của dân tộc',
    imageSrc: '/dong-ho/e61fa0b1e73050229e57c67697a37133.jpg',
    category: 'phong-tuc',
    tags: ['học chữ', 'truyền thống', 'hiếu học', 'phong tục'],
  },
  {
    id: 'le-tet-que-nha',
    name: 'Lễ Tết Quê Nhà',
    description: 'Gia đình sum họp ngày Tết, bánh chưng xanh, câu đối đỏ, mai vàng rực rỡ',
    imageSrc: '/dong-ho/fb8556adbecbd4f269cd4e755c11ec5d.jpg',
    category: 'phong-tuc',
    tags: ['Tết', 'gia đình', 'sum họp', 'phong tục'],
  },
]

export const CATEGORIES = [
  { id: 'tat-ca',     label: 'Tất cả' },
  { id: 'linh-vat',   label: 'Linh vật' },
  { id: 'con-nguoi',  label: 'Con người' },
  { id: 'thien-nhien',label: 'Thiên nhiên' },
  { id: 'phong-tuc',  label: 'Phong tục' },
]